#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jun 19 17:26:28 2019

@author: james
"""
import os
import matplotlib.pyplot as plt

dir_masks = '/home/james/Dropbox/ML/Insight/derm_assist/code/masks'
dir_images_all = '/home/james/Dropbox/ML/Insight/derm_assist/data/ISIC_2019_all/'
fnames = os.listdir(dir_masks)

import fnmatch


fnames_mask = fnmatch.filter(fnames, '*mask.npy')

image_num = 0
image_full = plt.imread(dir_images_all+fnames_mask[image_num][:-9]+'.jpg')
plt.figure()
plt.imshow(image_full)









